alert("Mi primer programa");
console.log("Mi primer programa");
const a=25;
const b=30;
const c=a+b;
console.log("La suma es:",c);
let d=5;
let e=7;
let f=a+b;
d=f+e;
f=d+e;//69
console.log("La suma es:",f+e,f);
console.log("La suma es:",d+e);
console.log("La resta es:",d-e);
console.log("La multiplicacion es:",d*e);
console.log("La division es:",d/e);
let valorA=parseInt(prompt("Intoduzca un numero"));
let valorB=prompt("Introduzca un numero");
let res=valorA+parseInt(valorB);
alert(res);
valorA=parseFloat(prompt("Intoduzca un numero"));
valorB=prompt("Introduzca un numero");
res=valorA+Number(valorB);
alert(res);
console.log(Boolean (0));
console.log(Boolean (1));
console.log(Boolean (""));
console.log(Boolean("hola"));